### ISSUE TITLE
MVP feature tracking (0.1 release)

### ISSUE THREAD

**Issue by jakmeier** [jakmeier/paddle#1]
Before releasing 0.1 on crates.io, these features should be implemented and tested. They cover the basic need for the paddlers browser game.

- [x] Frame management
- [x] 2D image drawing
- [x] Lyon support for complex shape drawing
- [x] Mouse clicks
- [x] Mouse movement for hover effects
- [x] Touch input
- [x] Keyboard events
- [x] Solution for half-transparent drawing

**Comment by jakmeier** [comment]
Released on crates.io
